# Generated by Django 5.1.2 on 2025-08-12 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_company_description_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
