# Generated by Django 5.1.2 on 2025-08-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_payment_momo_extra_data_payment_momo_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
