# Generated by Django 5.1.2 on 2025-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_reservationdetail_passenger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
